### PR TITLE
update cm on file I/O

### PR DESCRIPTION
**Pull request by dchiu911**
Changes:
- Dates changed for cm landing page
- Removed notes specific to last year's class
- Used `system.file()` to import `.tsv` data since class is on I/O

### CODE REVIEW

**Comment by jennybc** [comment]
Thanks @dchiu911. Can you have another look at this and add some info on using `readr` to bring delimited files in and out? I'd like to show that in addition to base functions.

**Comment by dchiu911** [comment]
Hi @jennybc 

I added some `readr` commands, but the resulting objects don't come up the same as the base functions. Maybe I'm not doing something correctly. Please have a look at the code in the latest commit?

Thanks,
Derek

**Comment by dchiu911** [comment]
Hi @jennybc

So I added a new block porting over material from 2013 and adding some `readr` content.

**Comment by jennybc** [comment]
Thanks! There are merge conflicts so I'll have to bring this in and integrate locally.

**Pull request closed without merging**
