### PR TITLE
Outline of basic shell add-on

### PR DESCRIPTION
**Pull request by BernhardKonrad**
To tackle [issue 30 in InstructorsOnly](https://github.com/STAT545-UBC/InstructorsOnly/issues/30)

### CODE REVIEW

**Comment by jennybc** [comment]
@daattali @ksamuk @oganm @npjc @dchiu911 @cheny19

Does one of you care to adopt this pull request and give it a review? We **should** have a page about "the shell". What it is and how to get into one, because it comes up alot in the git instructions. Once it exists, we should link to it in the obvious places from all the git stuff.

Mechanics advice:
You can read the "command line instructions" that GitHub provides for bringing a PR into your local repo. But most of you aren't STAT 545 owners yet :( Working on that. Lower tech solution: you could just fork this repo, make the new file, copy and paste from @BernhardKonrad's draft, make some edits/extensions, and make a new PR.

**Comment by oganm** [comment]
How detailed should the page be? I suppose instructions for getting to the shell outside Rstudio in different OSs would be helpful. A few more basic commands like mv cp? Should it include detailed shell functionality? Actual use of the shell for git purposes are already described [here](git07_git-usage.md). I cannot see the main issue yet since it's a private repo I think.

**Comment by npjc** [comment]
I can have a go later this eve if no-one else can. 

Some thoughts:
* Maybe just markdownify the reference guide in Appendix 3 [here](http://practicalcomputing.org/files/PCfB_Appendices.pdf)? Alternatively, style it according to the RStudio cheatsheets?
* other handy things off the top of my head:
  * also dragging a folder/file in to get the path
  * autocomplete with tab
* a motivating example (use case) demonstrating the awesomeness of using the shell by taking something time-consuming that most people do manually and doing it in bash.

**Comment by ksamuk** [comment]
@npjc While that guide is really awesome, it might be beyond the scope of what we'd want as a companion to git (specifically). What do others think? Fully agree that the dragging/autocomplete tips would be handy (also up arrow for history...much retyping happening today in class). I think the page @BernhardKonrad prepared is pitched at the right level, but it depends on what @jennybc is looking for.

PSA You can add "http://htmlpreview.github.io/?" to any Github HTML file to see a rendered version. 

e.g. You can see the a rendered version of the pull here:

http://htmlpreview.github.io/?https://github.com/STAT545-UBC/STAT545-UBC.github.io/blob/62df0d049b4c9edb7270f4d8db862b34460e638d/git08_shell.html

**Comment by BernhardKonrad** [comment]
As @ksamuk said, it depends on what @jennybc wants.

If we're following last year we're only touching what we need from the shell to make R, RStudio, git to work together. That can already be overwhelming to some. Later, when students are more comfortable with their set-up and we talk about automation (in particular, make) the power of the shell will become apparent.

**Comment by jennybc** [comment]
@ksamuk and @BernhardKonrad capture where I'm coming from. There are lots of great shell materials out there -- we could link to some!

But for this page, the goal is just to explain the "shell" jargon, go over how to get there, and show the very most basic commands they might need, i.e. the ones we mention in various places in the git set up instructions.

The present PR is very close -- I think that last list of command just needs to be fleshed out a bit. For example, looking at the git remotes and confirming there is a tracking branch. These are the things that can't be done from RStudio and can sometimes get people stuck.

Would be good to add a couple links to other full-blown materials on the shell.

**Comment by BernhardKonrad** [comment]
I added a little more detail, didn't see your PR in time, @npjc. Feel free to overwrite/merge my edits.

**Comment by ksamuk** [comment]
OK! I'm integrating this with the rest of the website (linking to it wherever it says "shell"). One slightly confusing thing. Why can't I see the new files from this PR in the master branch (e.g. git08_shell.md and git08_shell.html)? Is there another step that needs to be done? Should I just copy git08_shell.md into my local repo, rebuild and push?

**Comment by jennybc** [comment]
Hmmm I don't understand why those files aren't in master. I must conclude that I clobbered them with some overzealous work in my big refactor of all the git stuff. It was very late.

Yes please just re-add them.

**Comment by ksamuk** [comment]
Will do!

**Comment by jennybc** [comment]
They're also still in the basis_shell branch

https://github.com/STAT545-UBC/STAT545-UBC.github.io/tree/basic_shell

which I haven't deleted. So do whatever you find easiest.

**Comment by ksamuk** [comment]
Alrighty, I just pushed 1cf1da224689f04029851fb27220df630d12d2e1 which adds in links to the shell page all over the place (where appropriate, I tried not to be super redundant).

**Pull request merged**
